package main

// officialBaseSceneSpecs gives every bundled Heaven Studio prefab a basic
// extraction entry. These entries are intentionally asset-only: gameplay code
// still has to prove event timing, sounds, effects, and inputs against the C#
// source before a game is registered as playable.
var officialBaseSceneSpecs = map[string]sceneSpec{
	"agbSamuraiSlice":   basicOfficialSceneSpec("SamuraiSliceAgb", "agbSamuraiSlice.prefab"),
	"airboarder":        basicOfficialSceneSpec("Airboarder", "airboarder.prefab"),
	"animalAcrobat":     basicOfficialSceneSpec("AnimalAcrobat", "animalAcrobat.prefab"),
	"balloonHunter":     basicOfficialSceneSpec("BalloonHunter", "balloonHunter.prefab"),
	"basketballGirls":   basicOfficialSceneSpec("BasketballGirls", "basketballGirls.prefab"),
	"bigRockFinish":     basicOfficialSceneSpec("BigRockFinish", "bigRockFinish.prefab"),
	"blueBirds":         basicOfficialSceneSpec("BlueBirds", "blueBirds.prefab"),
	"boardMeeting":      basicOfficialSceneSpec("BoardMeeting", "boardMeeting.prefab"),
	"bonOdori":          basicOfficialSceneSpec("BonOdori", "bonOdori.prefab"),
	"bossaNova":         basicOfficialSceneSpec("BossaNova", "bossaNova.prefab"),
	"bouncyRoad":        basicOfficialSceneSpec("BouncyRoad", "bouncyRoad.prefab"),
	"builtToScaleDS":    basicOfficialSceneSpec("BuiltToScaleDS", "builtToScaleDS.prefab"),
	"builtToScaleRvl":   basicOfficialSceneSpec("BuiltToScaleRvl", "builtToScaleRvl.prefab"),
	"cannery":           basicOfficialSceneSpec("Cannery", "cannery.prefab"),
	"catchOfTheDay":     basicOfficialSceneSpec("CatchOfTheDay", "catchOfTheDay.prefab"),
	"catchyTune":        basicOfficialSceneSpec("CatchyTune", "catchyTune.prefab"),
	"chameleon":         basicOfficialSceneSpec("Chameleon", "chameleon.prefab"),
	"chargingChicken":   basicOfficialSceneSpec("ChargingChicken", "chargingChicken.prefab"),
	"clapTrap":          basicOfficialSceneSpec("ClapTrap", "clapTrap.prefab"),
	"clappyTrio":        basicOfficialSceneSpec("ClappyTrio", "clappyTrio.prefab"),
	"coinToss":          basicOfficialSceneSpec("CoinToss", "coinToss.prefab"),
	"cropStomp":         basicOfficialSceneSpec("CropStomp", "cropStomp.prefab"),
	"djSchool":          basicOfficialSceneSpec("DJSchool", "djSchool.prefab"),
	"dogNinja":          basicOfficialSceneSpec("DogNinja", "dogNinja.prefab"),
	"doubleDate":        basicOfficialSceneSpec("DoubleDate", "doubleDate.prefab"),
	"dressYourBest":     basicOfficialSceneSpec("DressYourBest", "dressYourBest.prefab"),
	"drummerDuel":       basicOfficialSceneSpec("DrummerDuel", "drummerDuel.prefab"),
	"drummingPractice":  basicOfficialSceneSpec("DrummingPractice", "drummingPractice.prefab"),
	"fallingWaffle":     basicOfficialSceneSpec("FallingWaffle", "fallingWaffle.prefab"),
	"fanClub":           basicOfficialSceneSpec("FanClub", "fanClub.prefab"),
	"figureFighter":     basicOfficialSceneSpec("FigureFighter", "figureFighter.prefab"),
	"fillbots":          basicOfficialSceneSpec("Fillbots", "fillbots.prefab"),
	"fireworks":         basicOfficialSceneSpec("Fireworks", "fireworks.prefab"),
	"firstContact":      basicOfficialSceneSpec("FirstContact", "firstContact.prefab"),
	"flipperFlop":       basicOfficialSceneSpec("FlipperFlop", "flipperFlop.prefab"),
	"forkLifter":        basicOfficialSceneSpec("ForkLifter", "forkLifter.prefab"),
	"freezeFrame":       basicOfficialSceneSpec("FreezeFrame", "freezeFrame.prefab"),
	"frogHop":           basicOfficialSceneSpec("FrogHop", "frogHop.prefab"),
	"frogPrincess":      basicOfficialSceneSpec("FrogPrincess", "frogPrincess.prefab"),
	"fruitBasket":       basicOfficialSceneSpec("FruitBasket", "fruitBasket.prefab"),
	"gardenDance":       basicOfficialSceneSpec("GardenDance", "gardenDance.prefab"),
	"gleeClub":          basicOfficialSceneSpec("GleeClub", "gleeClub.prefab"),
	"holeInOne":         basicOfficialSceneSpec("HoleInOne", "holeInOne.prefab"),
	"launchParty":       basicOfficialSceneSpec("LaunchParty", "launchParty.prefab"),
	"loveLab":           basicOfficialSceneSpec("LoveLab", "loveLab.prefab"),
	"loveLizards":       basicOfficialSceneSpec("LoveLizards", "loveLizards.prefab"),
	"loveRap":           basicOfficialSceneSpec("LoveRap", "loveRap.prefab"),
	"lumbearjack":       basicOfficialSceneSpec("Lumbearjack", "lumbearjack.prefab"),
	"magicGirl":         basicOfficialSceneSpec("MagicGirl", "magicGirl.prefab"),
	"mannequinFactory":  basicOfficialSceneSpec("MannequinFactory", "mannequinFactory.prefab"),
	"manzai":            basicOfficialSceneSpec("Manzai", "manzai.prefab"),
	"moaiDooWop":        basicOfficialSceneSpec("MoaiDooWop", "moaiDooWop.prefab"),
	"monkeyWatch":       basicOfficialSceneSpec("MonkeyWatch", "monkeyWatch.prefab"),
	"mrUpbeat":          basicOfficialSceneSpec("MrUpbeat", "mrUpbeat.prefab"),
	"nailCarpenter":     basicOfficialSceneSpec("NailCarpenter", "nailCarpenter.prefab"),
	"nightWalkAgb":      basicOfficialSceneSpec("NightWalkAgb", "nightWalkAgb.prefab"),
	"ninjaBodyguard":    basicOfficialSceneSpec("NinjaBodyguard", "ninjaBodyguard.prefab"),
	"nipInTheBud":       basicOfficialSceneSpec("NipInTheBud", "nipInTheBud.prefab"),
	"octopusMachine":    basicOfficialSceneSpec("OctopusMachine", "octopusMachine.prefab"),
	"packingPests":      basicOfficialSceneSpec("PackingPests", "packingPests.prefab"),
	"pajamaParty":       basicOfficialSceneSpec("PajamaParty", "pajamaParty.prefab"),
	"powerCalligraphy":  basicOfficialSceneSpec("PowerCalligraphy", "powerCalligraphy.prefab"),
	"quizShow":          basicOfficialSceneSpec("QuizShow", "quizShow.prefab"),
	"rapMen":            basicOfficialSceneSpec("RapMen", "rapMen.prefab"),
	"rhythmFighter":     basicOfficialSceneSpec("RhythmFighter", "rhythmFighter.prefab"),
	"rhythmRally":       basicOfficialSceneSpec("RhythmRally", "rhythmRally.prefab"),
	"rhythmSheriff":     basicOfficialSceneSpec("RhythmSheriff", "rhythmSheriff.prefab"),
	"rhythmTestGBA":     basicOfficialSceneSpec("RhythmTestGBA", "rhythmTestGBA.prefab"),
	"rhythmTweezers":    basicOfficialSceneSpec("RhythmTweezers", "rhythmTweezers.prefab"),
	"ringside":          basicOfficialSceneSpec("Ringside", "ringside.prefab"),
	"rockers":           basicOfficialSceneSpec("Rockers", "rockers.prefab"),
	"samuraiSliceNtr":   basicOfficialSceneSpec("SamuraiSliceNtr", "samuraiSliceNtr.prefab"),
	"samuraiSliceRvl":   basicOfficialSceneSpec("SamuraiSliceRvl", "samuraiSliceRvl.prefab"),
	"shootEmUp":         basicOfficialSceneSpec("ShootEmUp", "shootEmUp.prefab"),
	"showtime":          basicOfficialSceneSpec("Showtime", "showtime.prefab"),
	"sickBeats":         basicOfficialSceneSpec("SickBeats", "sickBeats.prefab"),
	"slotMonster":       basicOfficialSceneSpec("SlotMonster", "slotMonster.prefab"),
	"spaceSoccer":       basicOfficialSceneSpec("SpaceSoccer", "spaceSoccer.prefab"),
	"spaceball":         basicOfficialSceneSpec("SpaceBall", "spaceball.prefab"),
	"splashdown":        basicOfficialSceneSpec("Splashdown", "splashdown.prefab"),
	"sumoBrothers":      basicOfficialSceneSpec("SumoBrothers", "sumoBrothers.prefab"),
	"superSamuraiSlice": basicOfficialSceneSpec("SuperSamuraiSlice", "superSamuraiSlice.prefab"),
	"tapTroupe":         basicOfficialSceneSpec("TapTroupe", "tapTroupe.prefab"),
	"theDazzles":        basicOfficialSceneSpec("TheDazzles", "theDazzles.prefab"),
	"tossBoys":          basicOfficialSceneSpec("TossBoys", "tossBoys.prefab"),
	"tramAndPauline":    basicOfficialSceneSpec("TramAndPauline", "tramAndPauline.prefab"),
	"tunnel":            basicOfficialSceneSpec("Tunnel", "tunnel.prefab"),
	"valiantVolley":     basicOfficialSceneSpec("ValiantVolley", "valiantVolley.prefab"),
	"warioDeMambo":      basicOfficialSceneSpec("WarioDeMambo", "warioDeMambo.prefab"),
	"wizardsWaltz":      basicOfficialSceneSpec("WizardsWaltz", "wizardsWaltz.prefab"),
	"workingDough":      basicOfficialSceneSpec("WorkingDough", "workingDough.prefab"),
}

func init() {
	for id, spec := range officialBaseSceneSpecs {
		if _, ok := sceneSpecs[id]; !ok {
			sceneSpecs[id] = spec
		}
	}
}

func basicOfficialSceneSpec(dir, prefab string) sceneSpec {
	return sceneSpec{
		dir:             dir,
		prefab:          prefab,
		wantControllers: true,
	}
}
